window.GCAD={
  objects:[],selectedId:null,activeSketch:null,editId:null,editPoint:-1,nextId:1,undoStack:[],redoStack:[],sweepMode:null,
  settings:{showGrid:true,wireframe:false,snapGrid:true},camera:{yaw:-.72,pitch:.60,zoom:40,target:[0,0,0]},
  dragging:false,lastX:0,lastY:0,dragMoved:false,CLOSE_PX:10
};
(()=>{'use strict';const G=window.GCAD;G.$=id=>document.getElementById(id);G.canvas=G.$('canvas');G.ctx=G.canvas.getContext('2d');
G.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));G.add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];G.sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];G.mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];G.dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];G.cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];G.len=a=>Math.hypot(...a);G.norm=a=>{const l=G.len(a)||1;return a.map(v=>v/l)};G.deep=v=>JSON.parse(JSON.stringify(v));G.uid=()=>`o${G.nextId++}`;G.mesh=name=>({name,vertices:[],faces:[]});G.tri=(m,a,b,c)=>m.faces.push([a,b,c]);G.num=(id,f=0)=>{const v=parseFloat(G.$(id)?.value);return Number.isFinite(v)?v:f};
G.rotateX=(p,a)=>{const c=Math.cos(a),s=Math.sin(a);return[p[0],p[1]*c-p[2]*s,p[1]*s+p[2]*c]};G.rotateZ=(p,a)=>{const c=Math.cos(a),s=Math.sin(a);return[p[0]*c-p[1]*s,p[0]*s+p[1]*c,p[2]]};G.rotateView=p=>{let q=G.sub(p,G.camera.target);q=G.rotateZ(q,-G.camera.yaw);return G.rotateX(q,-G.camera.pitch)};G.project=(p,w,h)=>{const q=G.rotateView(p),s=Math.min(w,h)/G.camera.zoom;return[w/2+q[0]*s,h/2-q[1]*s,q[2]]};G.worldTop=(x,y)=>{const r=G.canvas.getBoundingClientRect(),s=Math.min(r.width,r.height)/G.camera.zoom;let wx=(x-r.width/2)/s+G.camera.target[0],wy=-(y-r.height/2)/s+G.camera.target[1];if(G.settings.snapGrid){wx=Math.round(wx*2)/2;wy=Math.round(wy*2)/2}return[wx,wy]};
G.setStatus=t=>{const e=G.$('statusText');if(e)e.textContent=t};G.showPrompt=t=>{const e=G.$('operationPrompt');if(e){e.textContent=t;e.style.display='block'}};G.hidePrompt=()=>{const e=G.$('operationPrompt');if(e)e.style.display='none'};G.objectById=id=>G.objects.find(o=>o.id===id);G.solidObjects=()=>G.objects.filter(o=>o.type==='solid');G.sketchObjects=()=>G.objects.filter(o=>o.type==='sketch');G.closedSketches=()=>G.sketchObjects().filter(o=>o.closed);
G.snapshot=()=>({objects:G.deep(G.objects),selectedId:G.selectedId,nextId:G.nextId});G.restore=s=>{G.objects=G.deep(s.objects||[]);G.selectedId=s.selectedId||null;G.nextId=s.nextId||1;G.activeSketch=null;G.editId=null;G.sweepMode=null;G.refreshAll()};G.mutate=(label,fn)=>{const before=G.snapshot();fn();G.undoStack.push({state:before,label});if(G.undoStack.length>60)G.undoStack.shift();G.redoStack=[];G.setStatus(label);G.refreshAll()};
G.setView=n=>{if(n==='top'){G.camera.yaw=0;G.camera.pitch=0}if(n==='front'){G.camera.yaw=0;G.camera.pitch=Math.PI/2}if(n==='right'){G.camera.yaw=Math.PI/2;G.camera.pitch=Math.PI/2}if(n==='iso'){G.camera.yaw=-.72;G.camera.pitch=.60}G.render()};
G.controlPoints=o=>o.geometry==='bezier'?(o.control||[]):(o.points||[]);G.bezierSamples=c=>{if(!c||c.length<3)return[];const[s,e,k]=c,out=[];for(let i=0;i<=48;i++){const t=i/48,u=1-t;out.push([u*u*s[0]+2*u*t*k[0]+t*t*e[0],u*u*s[1]+2*u*t*k[1]+t*t*e[1]])}return out};G.rebuild=o=>{if(o.geometry==='bezier')o.points=G.bezierSamples(o.control)};
G.drawGrid=(w,h)=>{if(!G.settings.showGrid)return;const half=Math.max(20,G.camera.zoom*.7),step=G.camera.zoom>80?10:G.camera.zoom>40?5:2;G.ctx.lineWidth=1;for(let i=-half;i<=half;i+=step){let a=G.project([i,-half,0],w,h),b=G.project([i,half,0],w,h);G.ctx.strokeStyle=Math.abs(i)<1e-6?'#526173':'#252b33';G.ctx.beginPath();G.ctx.moveTo(a[0],a[1]);G.ctx.lineTo(b[0],b[1]);G.ctx.stroke();a=G.project([-half,i,0],w,h);b=G.project([half,i,0],w,h);G.ctx.strokeStyle=Math.abs(i)<1e-6?'#526173':'#252b33';G.ctx.beginPath();G.ctx.moveTo(a[0],a[1]);G.ctx.lineTo(b[0],b[1]);G.ctx.stroke()}};
G.renderSketch=(o,w,h,selected=false,temp=false)=>{const pts=o.points||[];if(!pts.length)return;const c=G.ctx;c.lineWidth=selected?2.3:1.7;c.strokeStyle=temp?'#8dd6ff':selected?'#8fd3ff':'#67c7ff';if(o.closed&&pts.length>2){c.beginPath();pts.forEach((p,i)=>{const s=G.project([p[0],p[1],0],w,h);i?c.lineTo(s[0],s[1]):c.moveTo(s[0],s[1])});c.closePath();c.fillStyle=selected?'rgba(100,190,255,.16)':'rgba(70,170,230,.10)';c.fill()}c.beginPath();pts.forEach((p,i)=>{const s=G.project([p[0],p[1],0],w,h);i?c.lineTo(s[0],s[1]):c.moveTo(s[0],s[1])});if(o.closed&&pts.length>2)c.closePath();c.stroke();if(G.editId===o.id){const cps=G.controlPoints(o);if(o.geometry==='bezier'&&cps.length===3){c.save();c.setLineDash([4,4]);c.strokeStyle='#6f7f91';const a=G.project([cps[0][0],cps[0][1],0],w,h),b=G.project([cps[2][0],cps[2][1],0],w,h),d=G.project([cps[1][0],cps[1][1],0],w,h);c.beginPath();c.moveTo(a[0],a[1]);c.lineTo(b[0],b[1]);c.lineTo(d[0],d[1]);c.stroke();c.restore()}for(const p of cps){const s=G.project([p[0],p[1],0],w,h);c.fillStyle='#fff';c.strokeStyle='#2c8ed0';c.lineWidth=2;c.beginPath();c.arc(s[0],s[1],5,0,Math.PI*2);c.fill();c.stroke()}}};
G.renderMesh=(m,w,h,sel,tris)=>{const pv=m.vertices.map(v=>G.project(v,w,h));for(const f of m.faces){const a3=G.rotateView(m.vertices[f[0]]),b3=G.rotateView(m.vertices[f[1]]),c3=G.rotateView(m.vertices[f[2]]),n=G.norm(G.cross(G.sub(b3,a3),G.sub(c3,a3))),pa=pv[f[0]],pb=pv[f[1]],pc=pv[f[2]],sc=(pb[0]-pa[0])*(pc[1]-pa[1])-(pb[1]-pa[1])*(pc[0]-pa[0]);if(!G.settings.wireframe&&sc>0)continue;tris.push({pa,pb,pc,z:(pa[2]+pb[2]+pc[2])/3,n,sel})}};
G.render=()=>{const r=G.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),W=Math.max(1,Math.round(r.width*dpr)),H=Math.max(1,Math.round(r.height*dpr));if(G.canvas.width!==W||G.canvas.height!==H){G.canvas.width=W;G.canvas.height=H}const c=G.ctx;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,r.width,r.height);G.drawGrid(r.width,r.height);const tris=[];G.solidObjects().forEach(o=>G.renderMesh(o.mesh,r.width,r.height,o.id===G.selectedId,tris));tris.sort((a,b)=>a.z-b.z);for(const t of tris){c.beginPath();c.moveTo(t.pa[0],t.pa[1]);c.lineTo(t.pb[0],t.pb[1]);c.lineTo(t.pc[0],t.pc[1]);c.closePath();if(G.settings.wireframe){c.strokeStyle=t.sel?'#8fd3ff':'#d1ad4a';c.stroke()}else{const l=G.norm([.35,-.45,1]),u=G.clamp(.28+.72*Math.max(0,G.dot(t.n,l)),.22,1);c.fillStyle=t.sel?`rgb(${Math.round(90*u+40)},${Math.round(165*u+35)},${Math.round(235*u+20)})`:`rgb(${Math.round(205*u)},${Math.round(178*u)},${Math.round(92*u)})`;c.fill();c.strokeStyle=t.sel?'#8fd3ff':'#514627';c.lineWidth=t.sel?1:.35;c.stroke()}}G.sketchObjects().forEach(o=>G.renderSketch(o,r.width,r.height,o.id===G.selectedId));if(G.activeSketch){const tmp=G.activeSketch.mode==='curve'?{points:G.activeSketch.preview||[],closed:false}:{points:G.activeSketch.points,closed:false};G.renderSketch(tmp,r.width,r.height,false,true)}const v=G.$('viewInfo');if(v)v.innerHTML=`Sketch ${G.sketchObjects().length}<br>Solid ${G.solidObjects().length}<br>Zoom ${G.camera.zoom.toFixed(1)} mm`};
})();
