window.addEventListener('gcad-auth-ready',()=>{'use strict';const G=window.GCAD,$=G.$;
function fitAll(){const p=[];G.objects.forEach(o=>{if(o.type==='sketch')o.points.forEach(q=>p.push([q[0],q[1],0]));else p.push(...o.mesh.vertices)});if(!p.length){G.camera.target=[0,0,0];G.camera.zoom=40;G.render();return}let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];p.forEach(q=>q.forEach((v,i)=>{mn[i]=Math.min(mn[i],v);mx[i]=Math.max(mx[i],v)}));G.camera.target=mn.map((v,i)=>(v+mx[i])/2);G.camera.zoom=Math.max(8,Math.max(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2])*1.6);G.render()}
$('sketchTool').onclick=()=>G.startSketch();$('finishSketch').onclick=()=>G.finishSketch(false);$('cancelSketch').onclick=()=>G.finishSketch(true);$('finishEdit').onclick=G.finishEdit;
$('extrudeFocus').onclick=()=>$('extrudePanel').scrollIntoView({block:'nearest'});$('sweepFocus').onclick=()=>{const o=G.objectById(G.selectedId);if(!o||o.type!=='sketch'||o.closed){G.showPrompt('先に沿わせる線を選択してください');G.setStatus('スイープ: 先に開いた線を選択してください');setTimeout(()=>{if(!G.sweepMode)G.hidePrompt()},1500);return}G.sweepMode={pathId:o.id};$('sweepFocus').classList.add('active');G.showPrompt('面を選択してください');G.setStatus('スイープ: 面を選択してください')};
$('createExtrude').onclick=()=>{const p=G.objectById($('extrudeProfile').value),h=G.num('extrudeHeight',3);if(!p||!p.closed||h<=0){G.setStatus('押し出す面と高さを確認してください');return}G.mutate('押し出しを作成',()=>G.addSolid('押し出し '+(G.solidObjects().length+1),G.makeExtrude(p.points,h)))};$('boxFocus').onclick=()=>$('boxPanel').scrollIntoView({block:'nearest'});$('sphereFocus').onclick=()=>$('spherePanel').scrollIntoView({block:'nearest'});$('createBox').onclick=()=>{const x=G.num('boxX',10),y=G.num('boxY',8),z=G.num('boxZ',3);if(Math.min(x,y,z)<=0)return;G.mutate('四角を作成',()=>G.addSolid('四角 '+(G.solidObjects().length+1),G.makeBox(x,y,z)));fitAll()};$('createSphere').onclick=()=>{const x=G.num('sphereX',8),y=G.num('sphereY',8),z=G.num('sphereZ',8);if(Math.min(x,y,z)<=0)return;G.mutate('球体を作成',()=>G.addSolid('球体 '+(G.solidObjects().length+1),G.makeEllipsoid(x,y,z)));fitAll()};
$('deleteSelected').onclick=()=>{if(!G.selectedId)return;const o=G.objectById(G.selectedId);G.mutate((o?.name||'選択')+' を削除',()=>{G.objects=G.objects.filter(x=>x.id!==G.selectedId);G.selectedId=null;G.editId=null})};$('showGrid').onchange=e=>{G.settings.showGrid=e.target.checked;G.render()};$('wireframe').onchange=e=>{G.settings.wireframe=e.target.checked;G.render()};$('snapGrid').onchange=e=>G.settings.snapGrid=e.target.checked;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>G.setView(b.dataset.view));$('fitBtn').onclick=fitAll;
$('newBtn').onclick=()=>{if(G.objects.length&&!confirm('現在の作業内容を消して新規作成しますか？'))return;G.objects=[];G.selectedId=null;G.nextId=1;G.undoStack=[];G.redoStack=[];G.activeSketch=null;G.editId=null;G.sweepMode=null;G.camera={yaw:-.72,pitch:.60,zoom:40,target:[0,0,0]};$('editControls').style.display='none';$('sketchControls').style.display='none';G.hidePrompt();G.setStatus('空の作業空間を作成');G.refreshAll()};$('undoBtn').onclick=()=>{if(!G.undoStack.length)return;const cur=G.snapshot(),e=G.undoStack.pop();G.redoStack.push({state:cur,label:e.label});G.restore(e.state);G.setStatus('元に戻す: '+e.label)};$('redoBtn').onclick=()=>{if(!G.redoStack.length)return;const cur=G.snapshot(),e=G.redoStack.pop();G.undoStack.push({state:cur,label:e.label});G.restore(e.state);G.setStatus('やり直す: '+e.label)};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}$('saveBtn').onclick=()=>downloadBlob(new Blob([JSON.stringify({format:'g-CAD',version:'0.7',units:'mm',nextId:G.nextId,objects:G.objects},null,2)],{type:'application/json'}),'g-CAD-project.json');$('openBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());G.objects=d.objects||[];G.objects.forEach(o=>{if(o.type!=='sketch')return;o.closed=!!o.closed;if(o.geometry==='spline'&&o.nodes){G.rebuild(o);return}if(o.geometry==='bezier'&&o.control){o.nodes=o.control.map(p=>({p:[...p],corner:false}));o.geometry='spline';G.rebuild(o);return}const source=o.points||[];o.nodes=source.map(p=>({p:[...p],corner:o.geometry==='polyline'}));o.geometry='spline';G.rebuild(o)});G.nextId=d.nextId||1000;G.selectedId=null;G.undoStack=[];G.redoStack=[];G.refreshAll();fitAll();G.setStatus('プロジェクトを開きました')}catch{alert('g-CADプロジェクトを読み込めませんでした。')}e.target.value=''};
function stlText(){let out='solid g_CAD\n';for(const o of G.solidObjects()){const m=o.mesh;for(const f of m.faces){const a=m.vertices[f[0]],b=m.vertices[f[1]],c=m.vertices[f[2]],n=G.norm(G.cross(G.sub(b,a),G.sub(c,a)));out+=`  facet normal ${n[0]} ${n[1]} ${n[2]}\n    outer loop\n      vertex ${a[0]} ${a[1]} ${a[2]}\n      vertex ${b[0]} ${b[1]} ${b[2]}\n      vertex ${c[0]} ${c[1]} ${c[2]}\n    endloop\n  endfacet\n`}}return out+'endsolid g_CAD\n'}function exportSTL(){if(!G.solidObjects().length){alert('STLへ書き出す立体がありません。');return}downloadBlob(new Blob([stlText()],{type:'model/stl'}),'g-CAD-model.stl');G.setStatus('STLを書き出しました')}$('exportBtn').onclick=exportSTL;$('exportBtn2').onclick=exportSTL;
window.addEventListener('resize',G.render);window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(G.activeSketch){G.finishSketch(true);return}if(G.editId){G.finishEdit();return}if(G.sweepMode){G.sweepMode=null;$('sweepFocus').classList.remove('active');G.hidePrompt();G.setStatus('スイープをキャンセル');return}}if(e.key==='Enter'&&G.activeSketch)G.finishSketch(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undoBtn').click()}});G.refreshAll();G.setStatus('空の作業空間です。線はベジェ曲線で作成し、Ctrl+クリックで角を作れます。');
},{once:true});
